Zipped:
	@scala-cli run project.scala Zipped.sc
ZippedWatch:
	@scala-cli test --watch --revolver project.scala Zipped.test.scala

Trampoline:
	@scala-cli run project.scala Trampoline.sc
TrampolineWatch:
	@scala-cli test --watch --revolver project.scala Trampoline.test.scala

ParserCombinator:
	@scala-cli run project.scala ParserCombinator.sc
ParserCombinatorWatch:
	@scala-cli test --watch --revolver project.scala ParserCombinator.test.scala

Test:
	@scala-cli test project.scala *.test.scala

.PHONY: Zipped ZippedWatch Trampoline TrampolineWatch ParserCombinator ParserCombinatorWatch
