Zipped:
	@scala-cli run project.scala Zipped.sc
ZippedWatch:
	@scala-cli test --watch --revolver project.scala Zipped.test.scala

Eval:
	@scala-cli run project.scala Eval.sc
EvalWatch:
	@scala-cli test --watch --revolver project.scala Eval.test.scala

ParserCombinator:
	@scala-cli run project.scala ParserCombinator.sc
ParserCombinatorWatch:
	@scala-cli test --watch --revolver project.scala ParserCombinator.test.scala

Test:
	@scala-cli test project.scala *.test.scala

.PHONY: Zipped ZippedWatch Eval EvalWatch ParserCombinator ParserCombinatorWatch
